sudo: false
language: java
jdk:
- openjdk8
script:
- test/run.sh
notifications:
  slack:
    secure: lVvhvQjodgRPiifZtNokFAsYdK8Ll+ATqw+AOBujwzO0mieaAWILlsaRu+92oZZ4eNYygwU3kvN81geFnhoK3X7OXQYeSq+Kd0bGwusz4fm8AvNjDu8tAR6ZUqXT8wwDhFDKfauTw6d2AGcwtnPYKuLJFFIPPj6yGzXtrar83WNhjhNNg9/k/agXrESosFI3Qvx86TPq2Rd8ehOSgX4lx8Kaqc/VaBORQBKmwESeHJG6QN+KTTgl3s1vE8ZQuRUNNnRoKWgonA2THMiw/Vr7Ek7nLoYv8pTiqfuXk+AtPBFvjJLEAf0DaduGNSrnTJxoTqeX7RCBM5GTZvuXr7BDXrPqme0PpEmUzhNS1hgTCUE+fvKb6RCfSU/FJ73OEpJEf2alLCp2IurdYA1T84ZZQVQ4F3TlKVjxd1yZ8P/TWM9uXRs44pA0/W8yHh53qQSXcHjqN+uwy/18AysAJw5uopuDcUoryggcfBw4JWuCqrwUfhKCrhHjdxNP3tgBKnTrMnc5DzQ7ytZkrE88aHUiU6ubTWOSp8s1R11/UUOfsPHH6zV0CpKB55JgBHyhYIKtmzW3056kXZ5fIZlItrWXRY6eGqNN+JExKQpg+enJu4fnTEwOObW5ZSGoCwGGosejFaaMEO4yEr1OHI4orOuTaLYCXDyo51gE9xvxuEwxBR0=
